apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-over-kustomize
  name: nginx-over-kustomize
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-over-kustomize
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-over-kustomize
    spec:
      containers:
      - image: nginx
        name: nginx-over-kustomize
        ports:
        - containerPort: 80
        resources: {}
status: {}
