apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-over-kustomize
  name: nginx-over-kustomize
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-over-kustomize
  type: NodePort
status:
  loadBalancer: {}
